export const REGiSTRO_EXITOSO = 'REGiSTRO_EXITOSO';
export const REGiSTRO_ERROR = 'REGiSTRO_ERROR';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';