// PARA CREAR USUARIO
export const REGiSTRO_EXITOSO = 'REGiSTRO_EXITOSO';
export const REGiSTRO_ERROR = 'REGiSTRO_ERROR';

// PARA LIMPIAR
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

// PARA LOGIN
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// PARA USUARIO AUTENTICADO
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';

// PARA CERRAR SESSION
export const CERRAR_SESSION = 'CERRAR_SESSION';