// PARA CREAR USUARIO
export const REGiSTRO_EXITOSO = 'REGiSTRO_EXITOSO';
export const REGiSTRO_ERROR = 'REGiSTRO_ERROR';

// PARA LIMPIAR
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';

// PARA LOGIN
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// PARA USUARIO AUTENTICADO
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';

// PARA CERRAR SESSION
export const CERRAR_SESSION = 'CERRAR_SESSION';

// PARA LA SUBIDA DE ARCHIVOS
export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';

// CREAR ENLACEs
export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO';
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR';

// LIMPIAR VARIABLES
export const LIMPIAR_STATE = 'LIMPIAR_STATE';